<h3>This new page is generated by CRM/Healthmonitor/Page/Templates.php</h3>
1 {include file="CRM/Report/Page/TemplateList.tpl"}
{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>
2 {include file="CRM/Report/Page/InstanceList.tpl"}
{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>
