<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.octopus8.devices/xml/schema/CRM/Devices/05_AlertRule.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cd90f7dbf9bb1838efd0a9540f060ea0)
 */
use CRM_Devices_ExtensionUtil as E;

/**
 * Database access object for the AlertRule entity.
 */
class CRM_Devices_DAO_AlertRule extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_o8_device_alert_rule';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique AlertRule ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $contact_id;

  /**
   * Alert Rule Code
   *
   * @var string
   */
  public $code;

  /**
   * FK to Address Contact
   *
   * @var int
   */
  public $addressee_id;

  /**
   * FK to Alarm Rule
   *
   * @var int
   */
  public $rule_id;

  /**
   * Alert Title
   *
   * @var string
   */
  public $title;

  /**
   * Alert Message
   *
   * @var string
   */
  public $message;

  /**
   * @var bool
   */
  public $civicrm;

  /**
   * @var bool
   */
  public $email;

  /**
   * @var bool
   */
  public $sms;

  /**
   * @var bool
   */
  public $telegram;

  /**
   * @var bool
   */
  public $api;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_o8_device_alert_rule';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Alert Rules') : E::ts('Alert Rule');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'addressee_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'rule_id', 'civicrm_o8_alarm_rule', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique AlertRule ID'),
          'required' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.id',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'where' => 'civicrm_o8_device_alert_rule.contact_id',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'code' => [
          'name' => 'code',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Code'),
          'description' => E::ts('Alert Rule Code'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.code',
          'export' => TRUE,
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'add' => NULL,
        ],
        'addressee_id' => [
          'name' => 'addressee_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Address Contact'),
          'where' => 'civicrm_o8_device_alert_rule.addressee_id',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'rule_id' => [
          'name' => 'rule_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Alarm Rule'),
          'where' => 'civicrm_o8_device_alert_rule.rule_id',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'add' => NULL,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Title'),
          'description' => E::ts('Alert Title'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.title',
          'export' => TRUE,
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'add' => NULL,
        ],
        'message' => [
          'name' => 'message',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Message'),
          'description' => E::ts('Alert Message'),
          'required' => TRUE,
          'maxlength' => 1255,
          'size' => CRM_Utils_Type::HUGE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.message',
          'export' => TRUE,
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'add' => NULL,
        ],
        'civicrm' => [
          'name' => 'civicrm',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('CiviCRM'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.civicrm',
          'export' => TRUE,
          'default' => 'true',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'email' => [
          'name' => 'email',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Email'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.email',
          'export' => TRUE,
          'default' => 'false',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'sms' => [
          'name' => 'sms',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('SMS'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.sms',
          'export' => TRUE,
          'default' => 'false',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'telegram' => [
          'name' => 'telegram',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Telegram'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.telegram',
          'export' => TRUE,
          'default' => 'false',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'api' => [
          'name' => 'api',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Api'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_o8_device_alert_rule.api',
          'export' => TRUE,
          'default' => 'false',
          'table_name' => 'civicrm_o8_device_alert_rule',
          'entity' => 'AlertRule',
          'bao' => 'CRM_Devices_DAO_AlertRule',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'o8_device_alert_rule', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'o8_device_alert_rule', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_code' => [
        'name' => 'index_code',
        'field' => [
          0 => 'code',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_o8_device_alert_rule::1::code',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
