<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.octopus8.healthmonitor/xml/schema/CRM/Healthmonitor/HealthAlert.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:05a88d30b6b98c6d7ad0cb0cd043b0b9)
 */
use CRM_Healthmonitor_ExtensionUtil as E;

/**
 * Database access object for the HealthAlert entity.
 */
class CRM_Healthmonitor_DAO_HealthAlert extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_health_alert';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique HealthAlert ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $contact_id;

  /**
   * FK to Health Monitor Data
   *
   * @var int
   */
  public $health_monitor_id;

  /**
   * FK to Health Rule
   *
   * @var int
   */
  public $health_alert_rule_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_health_alert';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Health Alerts') : E::ts('Health Alert');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'health_monitor_id', 'civicrm_health_monitor', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'health_alert_rule_id', 'civicrm_health_alert_rule', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique HealthAlert ID'),
          'required' => TRUE,
          'where' => 'civicrm_health_alert.id',
          'table_name' => 'civicrm_health_alert',
          'entity' => 'HealthAlert',
          'bao' => 'CRM_Healthmonitor_DAO_HealthAlert',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'where' => 'civicrm_health_alert.contact_id',
          'table_name' => 'civicrm_health_alert',
          'entity' => 'HealthAlert',
          'bao' => 'CRM_Healthmonitor_DAO_HealthAlert',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'health_monitor_id' => [
          'name' => 'health_monitor_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Health Monitor Data'),
          'where' => 'civicrm_health_alert.health_monitor_id',
          'table_name' => 'civicrm_health_alert',
          'entity' => 'HealthAlert',
          'bao' => 'CRM_Healthmonitor_DAO_HealthAlert',
          'localizable' => 0,
          'FKClassName' => 'CRM_Healthmonitor_DAO_HealthMonitor',
          'add' => NULL,
        ],
        'health_alert_rule_id' => [
          'name' => 'health_alert_rule_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Health Rule'),
          'where' => 'civicrm_health_alert.health_alert_rule_id',
          'table_name' => 'civicrm_health_alert',
          'entity' => 'HealthAlert',
          'bao' => 'CRM_Healthmonitor_DAO_HealthAlert',
          'localizable' => 0,
          'FKClassName' => 'CRM_Healthmonitor_DAO_HealthAlertRule',
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'health_alert', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'health_alert', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
