-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_o8_alert`;
DROP TABLE IF EXISTS `civicrm_o8_alert_rule`;
DROP TABLE IF EXISTS `civicrm_o8_alarm`;
DROP TABLE IF EXISTS `civicrm_o8_alarm_rule`;
DROP TABLE IF EXISTS `civicrm_o8_device_data`;
DROP TABLE IF EXISTS `civicrm_o8_device`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_o8_device
-- *
-- * o8 Device
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_device` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Device ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `code` varchar(255) NOT NULL COMMENT 'Unique Device Code',
  `device_type_id` int NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_device_code`(code),
  CONSTRAINT FK_civicrm_o8_device_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_device_data
-- *
-- * Device Data
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_device_data` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Device Data ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `date` datetime NOT NULL COMMENT 'Device Data Time',
  `device_id` int unsigned NOT NULL COMMENT 'FK to Device',
  `sensor_id` int NOT NULL DEFAULT 1,
  `sensor_value` decimal(20,2) NOT NULL COMMENT 'Sensor Value',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_device_data_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_o8_device_data_device_id FOREIGN KEY (`device_id`) REFERENCES `civicrm_o8_device`(`id`) ON DELETE RESTRICT
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_alarm_rule
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_alarm_rule` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique AlarmRule ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_alarm_rule_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_alarm
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_alarm` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Alarm ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_alarm_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_alert_rule
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_alert_rule` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique AlertRule ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_alert_rule_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_o8_alert
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_o8_alert` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Alert ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_o8_alert_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
